# Generated by Django 3.0.5 on 2020-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('designation', models.CharField(max_length=155)),
                ('location', models.CharField(max_length=155)),
                ('servicestart', models.DateTimeField(blank=True, default=None)),
                ('serviceends', models.DateTimeField(blank=True, default=None)),
            ],
            options={
                'ordering': ['servicestart'],
            },
        ),
    ]
